apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "azcluster1"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "azcluster1"
    spec:
      containers:
        - name: "azcluster1"
          image: "azkntestrepo.azurecr.io/azcluster1"
          ports:
          - containerPort: 8080