apiVersion: v1
kind: Service
metadata:
    name: "azcluster1"
    labels:
        app: "azcluster1"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "azcluster1"